server {
    listen 80;

    location /analitic/ {
        proxy_pass http://analitic:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /event-producer/ {
        proxy_pass http://event-producer:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}